### ISSUE TITLE
Unable to install Plugin

### ISSUE THREAD

**Issue by thephilluk** [luisr9/redmine_private_issues#2]
Hey there, 
i am currently unable to install the Plugin.
i am running the Redmine instance in a Docker container
Docker-compose.yml:
```
version: '2'

services:
  postgresql:
    image: sameersbn/postgresql:latest
    environment:
    - DB_USER=redmin
    - DB_PASS=password
    - DB_NAME=redmine_production
    volumes:
    - /srv/docker/redmine/postgresql:/var/lib/postgresql

  redmine:
    build: ./
    image: sameersbn/redmine:latest
    depends_on:
    - postgresql
    environment:
    - TZ=Europe/Berlin

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=redmin
    - DB_PASS=password
    - DB_NAME=redmine_production
    - DB_SSL_MODE=prefer
    - REDMINE_PLUGINS_MIGRATE=true

    - REDMINE_PORT=10083
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUP_SCHEDULE=
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=

    - SMTP_ENABLED=false
    - SMTP_METHOD=smtp
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=handmaderoleplay@gmail.com
    - SMTP_PASS=6To6vy729NndDuwg9oEz
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=handmaderoleplay@gmail.com
    - IMAP_PASS=6To6vy729NndDuwg9oEz
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

    ports:
    - "10083:80"
    volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
    - /srv/docker/redmine/redmine-logs:/var/log/redmine
```

i Downloaded the Plugin ZIP file to the Plugins folder, unzipped it. it now is in `redmine/plugins/redmine_private_issues`
whenever i try to start the Container, i get the following Log:
```
Initializing logdir...

Initializing datadir...

Symlinking dotfiles...

Installing configuration templates...

Configuring redmine...

Configuring redmine::database

Configuring redmine::unicorn...

Configuring redmine::secret_token...

Generating a session token...

Note:

  All old sessions will become invalid.

  Please specify the REDMINE_SECRET_TOKEN parameter for persistence.

  **SHOULD** be defined if you have a load-balancing Redmine cluster.

Configuring redmine::max_concurrent_ajax_uploads...

Configuring redmine::sudo_mode...

Configuring redmine::autologin_cookie...

Configuring redmine::backups...

Configuring redmine::rmagic::font...

Configuring nginx...

Configuring nginx::redmine...

Installing plugins...

Installing gems required by plugins...

You are replacing the current local value of without, which is currently "development:test"

Migrating plugins. Please be patient, this could take a while...

rake aborted!

LoadError: cannot load such file -- redmine_private_issues/hooks/controller_issues_new_before_save_hook.rb

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'

/home/redmine/redmine/plugins/redmine_private_issues/init.rb:15:in `<top (required)>'

/home/redmine/redmine/lib/redmine/plugin_loader.rb:31:in `load'

/home/redmine/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'

/home/redmine/redmine/lib/redmine/plugin_loader.rb:108:in `each'

/home/redmine/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `instance_exec'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `catch'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `block in default_terminator'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:199:in `block in halting'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `block in invoke_before'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `each'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `invoke_before'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:105:in `run_callbacks'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/reloader.rb:88:in `prepare!'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.6/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'

/home/redmine/redmine/config/environment.rb:16:in `<top (required)>'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.6/lib/rails/application.rb:367:in `require_environment!'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.6/lib/rails/application.rb:533:in `block in run_tasks_blocks'

/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Tasks: TOP => redmine:plugins:migrate => environment

(See full trace by running task with --trace)
```
